[build]
  publish = "site"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  publish = "site"
  functions = "netlify/functions"
